ktor {
  development = true
  deployment {
    port = 8082 # Port for notification-service
  }
  application {
    modules = [ com.ktormart.notificationservice.ApplicationKt.module ]
  }
}

rabbitmq {
  host = "localhost"
  port = 5672
  username = "guest"
  password = "guest"
  queueName = "user.events.queue"
}