ktor {
  development = true
  deployment {
    port = 8080 # Gateway runs on the main port 8080
  }
  application {
    modules = [com.ktormart.gateway.ApplicationKt.module]
    serviceName = "gateway"
  }
}

consul {
  host = "localhost"
  port = 8500
}

# Routing rules for our microservices
services {
  user-service {
    path = "/api/v1/users" # Requests starting with this path will be routed
    rewrite = "/users"    # The path will be rewritten to this before forwarding
  }
}